# Generated by Django 2.1.3 on 2020-10-01 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=2)),
                ('important_chars', models.TextField(blank=True)),
                ('capital', models.CharField(default='not specified', max_length=200)),
                ('other_areas', models.TextField(default='not specified')),
                ('cost_voting', models.CharField(default='not specified', max_length=20)),
                ('congressional_makeup', models.TextField(blank=True)),
                ('important_congressional_elections', models.TextField(blank=True)),
                ('electoral_votes', models.IntegerField(default=-1)),
                ('rv_dems', models.FloatField(default=-1)),
                ('rv_reps', models.FloatField(default=-1)),
                ('rv_other', models.FloatField(default=-1)),
                ('senator_1', models.CharField(default='not specified', max_length=100)),
                ('senator_1_party', models.CharField(choices=[('D', 'D'), ('R', 'R'), ('I', 'I')], default='not specified', max_length=1)),
                ('senator_2', models.CharField(default='not specified', max_length=100)),
                ('senator_2_party', models.CharField(choices=[('D', 'D'), ('R', 'R'), ('I', 'I')], default='not specified', max_length=1)),
                ('mailin_reason', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Yes, with exceptions', 'Yes, with exceptions')], default='not specified', max_length=40)),
                ('mailin_notarization', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Yes, with exceptions', 'Yes, with exceptions')], default='not specified', max_length=40)),
                ('mainin_automated', models.BooleanField(default=False)),
                ('mailin_id', models.BooleanField(default=False)),
                ('person_id', models.BooleanField(default=False)),
                ('mainin_deadline', models.DateTimeField(blank=True, null=True)),
                ('must_be_recieved_by_above', models.BooleanField(default=False)),
                ('turn_in_method', models.CharField(default='not specified', max_length=60)),
                ('pres_election_history', models.TextField(blank=True)),
                ('description', models.TextField(default='not specified')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.State')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
