# Generated by Django 2.1.3 on 2020-10-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201001_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='value',
            field=models.FloatField(default=-1),
        ),
    ]
