# Generated by Django 2.1.3 on 2020-10-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_demographic_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousElection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('percent_dems', models.FloatField()),
                ('percent_reps', models.FloatField()),
                ('dem_candiate', models.CharField(max_length=100)),
                ('rep_candidate', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='important_chars',
        ),
        migrations.RemoveField(
            model_name='state',
            name='pres_election_history',
        ),
        migrations.RemoveField(
            model_name='state',
            name='senator_1',
        ),
        migrations.RemoveField(
            model_name='state',
            name='senator_1_party',
        ),
        migrations.RemoveField(
            model_name='state',
            name='senator_2',
        ),
        migrations.RemoveField(
            model_name='state',
            name='senator_2_party',
        ),
        migrations.AddField(
            model_name='previouselection',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State'),
        ),
    ]
