# Generated by Django 2.1.3 on 2020-10-06 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201005_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statepoll',
            old_name='time',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='statepoll',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
