# Generated by Django 2.1.3 on 2020-10-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201005_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='core.State'),
        ),
        migrations.AlterField(
            model_name='houseelection',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houseElections', to='core.State'),
        ),
        migrations.AlterField(
            model_name='previouselection',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastElections', to='core.State'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='core.State'),
        ),
        migrations.AlterField(
            model_name='senateelection',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senateElections', to='core.State'),
        ),
        migrations.AlterField(
            model_name='senator',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senators', to='core.State'),
        ),
        migrations.AlterField(
            model_name='statepoll',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='core.State'),
        ),
    ]
