# Generated by Django 2.1.3 on 2020-10-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201007_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='biden2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='trump2',
            field=models.FloatField(default=0),
        ),
    ]
