# Generated by Django 3.1.2 on 2020-10-09 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201009_1425'),
        ('core', '0012_auto_20201009_1842'),
    ]

    operations = [
    ]
