# Generated by Django 2.1.3 on 2020-10-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201010_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='variance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statepoll',
            name='moe',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statepoll',
            name='n',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
