# Generated by Django 2.1.3 on 2020-10-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201009_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='mean2',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='variance2',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
