# Generated by Django 2.1.3 on 2020-10-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201009_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='mean',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction',
            name='variance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction2',
            name='mean',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction2',
            name='variance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
