# Generated by Django 2.1.3 on 2020-10-12 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201012_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_win', models.FloatField()),
                ('dem_win', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
