# Generated by Django 3.1.2 on 2020-10-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_nationalprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='bpi2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
