# Generated by Django 3.1.2 on 2020-10-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_state_bpi2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.TextField()),
            ],
        ),
    ]
