# Generated by Django 3.1.2 on 2020-10-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_statepoll_moe'),
    ]

    operations = [
        migrations.AddField(
            model_name='statepoll',
            name='cd2',
            field=models.BooleanField(default=False),
        ),
    ]
