# Generated by Django 2.1.3 on 2020-10-13 14:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_statepoll_cd2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorrelationMatrix',
        ),
        migrations.RemoveField(
            model_name='statepoll',
            name='cd2',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='statepoll',
            name='moe',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='core.State'),
        ),
    ]
