# Generated by Django 2.1.3 on 2020-10-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_featured_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
